### ISSUE TITLE
The associatedSites could communicate between each other?

### ISSUE THREAD

**Issue by emerson-paiva** [GoogleChrome/related-website-sets#105]
Hi everyone 👋🏼 

I'm preparing to submit changes to the `related_website_sets.JSON`, but I have a doubt if I set the object like this:

```json
{
      "contact": "email@email.com",
      "primary": "https://primary.com",
      "associatedSites": [
        "https://secondarysite.com",
        "https://anothersite.com"
      ],
      "rationaleBySite": {
        ...
      }
 }
```

We have an **associatedSite**: `secondarysite.com` that sends cookies as a third-party cookie to another site associatedSite `anothersite.com`, If the pull request is merged, the communication between the associatedSites is gonna work? Or do I need to set the `secondarysite.com` as primary?

**Comment by cfredric** [comment]
To answer your direct question - in this respect, there is no difference between the primary site and associated sites. (The only difference comes into play when Chrome does internal housekeeping as a set changes over time, but that's not involved here.) So the RWS functionality will be the same for you.

However, I want to point out that RWS doesn't *perform* any cross-site communication. I.e., setting up a RWS will not cause the cookies belonging to `secondarysite.com` to start being sent to `anothersite.com`. If you want to share that data, you will have to share it yourself, e.g. by sending a `window.postMessage` from a `secondarysite.com` iframe to a `anothersite.com` frame.

(RWS only lowers the user friction of using the [Storage Access API](https://github.com/privacycg/storage-access), which is all about restoring *access* to third-party cookies, as the name suggests - but doesn't dictate what to do once access has been restored.)

To see whether RWS enables the functionality you're looking for, I highly recommend testing locally first, before creating and submitting a pull request here. Local testing instructions can be found here: https://developer.chrome.com/docs/privacy-sandbox/related-website-sets-integration/#example

**Comment by emerson-paiva** [comment]
@cfredric **thanks** a lot for the quick and high-quality answer. We use the `postMessage` to communicate between the apps.

I'm going to test it before submitting it, thanks again.

**Comment by emerson-paiva** [comment]
Hi @cfredric, I hope you're doing well. I did some tests here and in fact, we use the cookie as third-party, setting the cookie in the `https://secondarysite.com` as Secure and SameSite = None. I thought defining the RWS the iframe still gonna have access if the third-party is disabled. 

My app didn't work as expected, do know if I have to pass the cookie as you mentioned before using `postMessage`?

**Comment by cfredric** [comment]
Hi @emerson-paiva, I'm not sure I understand the setup you're describing. Can you clarify:

* What do you mean by "if the third-party is disabled"? You mean if third-party cookies are blocked?
* You said "we use the cookie as third-party, setting the cookie in the `https://secondarysite.com` as Secure and SameSite = None." Can you verify that after setting the cookie, you can read it via `document.cookie` in the iframe?
* Can you verify that the iframe has called `document.requestStorageAccess()` before trying to set the cookie?

Re: whether you need to pass the cookie around via `postMessage`, I can't answer that, since I don't know how your app is intended to work.

**Comment by DariusGa** [comment]
> To answer your direct question - in this respect, there is no difference between the primary site and associated sites. (The only difference comes into play when Chrome does internal housekeeping as a set changes over time, but that's not involved here.) So the RWS functionality will be the same for you.
> 
> However, I want to point out that RWS doesn't _perform_ any cross-site communication. I.e., setting up a RWS will not cause the cookies belonging to `secondarysite.com` to start being sent to `anothersite.com`. If you want to share that data, you will have to share it yourself, e.g. by sending a `window.postMessage` from a `secondarysite.com` iframe to a `anothersite.com` frame.
> 
> (RWS only lowers the user friction of using the [Storage Access API](https://github.com/privacycg/storage-access), which is all about restoring _access_ to third-party cookies, as the name suggests - but doesn't dictate what to do once access has been restored.)
> 
> To see whether RWS enables the functionality you're looking for, I highly recommend testing locally first, before creating and submitting a pull request here. Local testing instructions can be found here: https://developer.chrome.com/docs/privacy-sandbox/related-website-sets-integration/#example

Tutti i giorni mattina e sera . 
3000 la mattina 
 3.000 il pomeriggio.

**Comment by LolyPopToyou** [comment]
> Hi everyone 👋🏼
> 
> I'm preparing to submit changes to the `related_website_sets.JSON`, but I have a doubt if I set the object like this:
> 
> ```json
> {
>       "contact": "email@email.com",
>       "primary": "https://primary.com",
>       "associatedSites": [
>         "https://secondarysite.com",
>         "https://anothersite.com"
>       ],
>       "rationaleBySite": {
>         ...
>       }
>  }
> ```
> 
> We have an **associatedSite**: `secondarysite.com` that sends cookies as a third-party cookie to another site associatedSite `anothersite.com`, If the pull request is merged, the communication between the associatedSites is gonna work? Or do I need to set the `secondarysite.com` as primary?
