### ISSUE TITLE
Unable to submit CLA

### ISSUE THREAD

**Issue by kwliang1** [GoogleChrome/related-website-sets#131]
I'm repeatedly unable to sign the corresponding CLA.   I've tried creating both a public and private group.   On every initial submission it says that a server error occurred, and then every subsequent attempt shows that "a CLA has already been submitted for this group".

Please advise.

**Comment by johannhof** [comment]
Hey, sorry about that. Most folks are out for thanksgiving until Monday and I'm not very familiar with the CLA setup, but did you follow the steps outlined at https://github.com/GoogleChrome/related-website-sets/pull/129/checks?check_run_id=18950087747? Specifically, there is some guidance on "I've signed the CLA, but it's still showing me as unsigned.", did you follow that?
