### ISSUE TITLE
Should requestStorageAccess request without user interaction?

### ISSUE THREAD

**Issue by emerson-paiva** [GoogleChrome/related-website-sets#153]
Hi everyone. I'm testing the `requestStorageAccess` using [this](https://developers.google.com/privacy-sandbox/3pcd/related-website-sets-integration#how_to_test_locally) document as a reference and I thought that by defining `associatedSites` we don't need users interactions to access the cookies. Still, I'm receiving `prompt` instead of.

<img width="843" alt="Screenshot 2023-12-04 at 17 38 48" src="https://github.com/GoogleChrome/related-website-sets/assets/23361175/c47f15fd-9017-4d07-945c-b2dcc3b82efd">

Am I doing something wrong or is this correct, do we need the user's interaction?

**Comment by cfredric** [comment]
Hi @emerson-paiva,

Chrome still does require the user's gesture if that's the first time `requestStorageAccess()` has been called, even within a RWS. Once the permission is `"granted"`, Chrome won't require the user gesture anymore, though.

You should be able to click the "Click for cookies" button and get storage access granted without a prompt (assuming you used the right `--use-related-website-set=` or `--use-first-party-set=` command line switch). Then if you refresh the page, you should see the permission is `"granted"`.

----

For a full description of Chrome's `requestStorageAccess()` implementation, please see https://github.com/cfredric/chrome-storage-access-api, specifically [this section](https://github.com/cfredric/chrome-storage-access-api#requesting-storage-access-permission).

**Comment by emerson-paiva** [comment]
Hi @cfredric,

I did the implementation, and now we have a page used for the user to interact with the button and `requestStorageAccess` on click, the request is working well, I receive the `granted` and `undefined` when the promise is resolved, and after that the user navigates to the page that needs the cookies, but I still can't access it. 

I'm following [this](https://developers.google.com/privacy-sandbox/3pcd/related-website-sets-integration#verify_that_you_have_access_to_cross-site_cookies) doc and the implementation you had sent before.

**Comment by cfredric** [comment]
Hi,

Can you confirm that the iframe that wants access to its cookies is also calling `document.requestStorageAccess`? For security reasons, that iframe does not *implicitly* get access to cookies except in very narrow circumstances. Please see this section in the docs: https://developers.google.com/privacy-sandbox/3pcd/related-website-sets-integration#per_frame_model

**Comment by emerson-paiva** [comment]
Hi, yes, the iframe is calling the `document.requestStorageAcess`.

Following the docs:
> Refreshing, reloading, or otherwise recreating the iframe will require requesting access again.

My iframe is an ASP.NET webform app, so every page has his own router and renders a completely new page/URL when using navigation, I'm gonna need to call in every page?

Right now my page looks like this:
1. A secondary page to user interact and requestStorageAccess **(AllowCookies.aspx)**
2. A href link so the users could click to navigate to the page that requires cookies (this page is not calling the `document.requestStorageAccess`) **(Categories.aspx)**

<img width="321" alt="Screenshot 2024-01-04 at 13 47 27" src="https://github.com/GoogleChrome/related-website-sets/assets/23361175/0d471d7f-9bf3-41eb-8da4-712644a08eb1">

**Comment by zamry09** [comment]
Pada Jum, 5 Jan 2024, 12:49 PG Emerson Paiva ***@***.***>
menulis:

**Comment by cfredric** [comment]
> I'm gonna need to call in every page?

Yes*. Please have a look at https://github.com/cfredric/storage-access-headers and let me know if that proposal would be useful to you, to avoid calling `document.requestStorageAccess()` in each iframe.

*If your iframes navigate *themselves*, and those navigations don't involve cross-origin redirects, then they won't need to call `requestStorageAccess()` again. There's a demo of this behavior on https://rws-member-1.glitch.me/request-storage-access.html (see the `navigate back here again` link). It looks like your pages might be able to take advantage of this.

**Comment by TheJKFever** [comment]
Would using `requestStorageAccessFor` act any differently than `requestStorageAccess` in that it won't require user interaction? It seems some places I'm reading like in here: https://github.com/cfredric/chrome-storage-access-api?tab=readme-ov-file implies that `requestStorageAccessFor` will not require user interaction. Is that right?

**Comment by cfredric** [comment]
> Would using `requestStorageAccessFor` act any differently than `requestStorageAccess` in that it won't require user interaction?

No; both APIs require a user interaction if permission has not yet been granted. A user gesture is one of the baseline requirements Chrome checks before granting a new permission (or prompting the user if they'd like to grant permission).

If the permission has already been granted (either by the user, or by the user agent on the user's behalf [e.g. via Related Website Sets]), then neither API requires a user gesture.

**Comment by emerson-paiva** [comment]
Hi @cfredric, thanks for the answers. I was doing some tests and the only way that worked for me was:

- Accessing `mylegacyapp.com` directly
- Defining the cookies I need it
- Go to `mynewapp.com/path-that-has-legacy-app-as-iframe`
- The iframe grants access to the cookie that is defined into `mylegacyapp.com`

I thought that the behaviour was like this:
- Accessing `mynewapp.com`
- Defining the cookies I need it
- Go to `mynewapp.com/path-that-has-legacy-app-as-iframe`
- The iframe grants access to the cookie that is defined into `mynewapp.com`

Without the need to access the old app, when I tried I received the following error:
> requestStorageAccess: Request denied because the embedded site has never been interacted with as a top-level context

Is the second case not possible?

**Comment by cfredric** [comment]
In your setup, it sounds like `mylegacyapp.com` is the site that has to access the cookies. If so, then it's also the one that has to define them.

RWS does not allow one site to read another site's cookies; that would be a huge security issue as it would violate the [Same Origin Policy](https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy). So `mylegacyapp.com` cannot read cookies that were defined by `mynewapp.com`, even if they're in the same RWS.

>> requestStorageAccess: Request denied because the embedded site has never been interacted with as a top-level context

Just FYI: if you're seeing this error, it means you haven't defined your RWS properly (so Chrome doesn't know about it). This error is only shown for non-RWS cases.

You can check `chrome://system` to see what RWSes Chrome is aware of, in order to verify whether your RWS is set up as you expect.
