### ISSUE TITLE
ServiceSites and related-website-set.json

### ISSUE THREAD

**Issue by fcurtiItaliaonline** [GoogleChrome/related-website-sets#214]
Some questions about RWS and services

Is allowed that one domain is configured as serviceSites for more than 1 primary domains? ( I think/hope yes)
Does serviceSites needs the /.well-known/related-website-set.json? (i think don't)

Thanks in advance

**Comment by cfredric** [comment]
Hi @fcurtiItaliaonline,

> Is allowed that one domain is configured as serviceSites for more than 1 primary domains? ( I think/hope yes)

Unfortunately no. A domain may only appear in one RWS at a time; no domain may be listed in 2 or more sets at the same time. See [the submission guidelines](https://github.com/GoogleChrome/related-website-sets/blob/main/RWS-Submission_Guidelines.md#set-level-technical-validation) for details, in particular "Each domain must not already be present in the [canonical RWS list.](https://github.com/googlechrome/first-party-sets/blob/main/related_website_sets.JSON)".

> Does serviceSites needs the /.well-known/related-website-set.json? (i think don't)

Yes, the `related-website-set.json` file is required for service sites as well. See again [the submission guidelines](https://github.com/GoogleChrome/related-website-sets/blob/main/RWS-Submission_Guidelines.md#set-level-technical-validation), in particular "Each domain must satisfy the /.well-known/ metadata requirement:".
