### ISSUE TITLE
RWS propagation on chrome

### ISSUE THREAD

**Issue by fcurtiItaliaonline** [GoogleChrome/related-website-sets#260]
How often and when Chrome update the last relase of RWS Json?
Thanks in advance

**Comment by thezedwards** [comment]
timeline appears to be 2-3 weeks based on : https://github.com/GoogleChrome/related-website-sets/blob/main/RWS-Submission_Guidelines.md

"If a set submission passes all technical checks successfully, the submitter will be notified that their PR was successful on GitHub. At this time, approved PRs will be manually merged in batches to the canonical RWS list once per week (Tuesdays at 12pm Eastern Time (ET)), excluding during holidays."
...
"Chrome consumes the canonical RWS list on a regular basis (every 2 weeks) and ships it to clients as an updateable component. Individual clients (with internet access) will refresh the list they apply each time they restart, or on start-up, if newly downloaded."

**Comment by fcurtiItaliaonline** [comment]
Thank for the answer
