### ISSUE TITLE
RWS PR# 418 Not Working! 

### ISSUE THREAD

**Issue by vn31699** [GoogleChrome/related-website-sets#424]
Related to the successfully merged PR 'RWS entry for John Deere #418', we are still seeing the 3rd party calls to domain .johndeere.com from first party .deere.com applications being blocked with the below Chrome (126+ version) flags. Can you please help understand why this is not working, is there anything missing and how to test so that calls between our RWS domains not blocked with the below flags ?
#third-party-cookie-deprecation-trial -> enabled 
#tracking-protection-3pcd -> enabled 
#tpcd-metadata-grants -> disabled 
#flags#tpcd-heuristics-grants->  disabled

**Comment by sjledoux** [comment]
Even though entry #418 has been merged, [it takes some time](https://github.com/GoogleChrome/related-website-sets/blob/main/RWS-Submission_Guidelines.md#browser-behavior) for the RWS list to be consumed by the Chrome browser and shipped to clients. I would expect this problem to resolve in the near future as the list migrates into the browser, but if you continue to experience this problem after 2 weeks please reach out again on this thread and we can address this in more detail.

**Comment by vn31699** [comment]
Thank you so much for the clarification, will monitor and get back.

**Comment by CrabbyJim** [comment]
Yes. Please take advantage of this opportunity for you to know about it and
see how they feel free to give them as they have been busy for you and your
new place to be in the job completed so you will have to wait until the end
of next step Google will try again later to provide appropriate information
about your business management program installed by each individual and see
how they feel about it when you're ready to talk more about this
information  and how much they have done for us and our mission allows us
to get the other stuff done by each individual and then go through the
process of getting to know each individual and make it easier for you to
know that you don't have to worry about me or anything else that would be
there and they will send it out tomorrow morning to let them know about my
life and see what happens

**Comment by cfredric** [comment]
Hi,

In the future, we recommend testing locally with the instructions [here](https://developers.google.com/privacy-sandbox/3pcd/related-website-sets-integration#how_to_test_locally) before you submit your PR, so that you don't run into this kind of issue.

Re: those Chrome flags, yes, RWS works when those flags are enabled. Chrome uses RWS to automatically grant storage access via [`document.requestStorageAccess()`](https://developers.google.com/privacy-sandbox/3pcd/related-website-sets-integration#check_and_request_storage_access), so you should see those promises resolve (and then be able to access your cookies in cross-site contexts). Alternatively, you could use `document.requestStorageAccessFor()`, as well.

**Comment by vn31699** [comment]
Hi, 
Will do, and thanks for the suggestion. As mentioned in the instructions, we tested with just one flag, 'test-third-party-cookie-phaseout,' instead of the four flags mentioned above. It works as expected, and calls between our domains are not being blocked, including the app within the iframe. Based on these results, we are unable to conclude that testing with just one flag, 'test-third-party-cookie-phaseout,' would suffice for RWS allowing cookies between our domains when fully enforced, or it might block since it is not working with all the four flags mentioned above. Can you please advise?

**Comment by cfredric** [comment]
Hm, the issue may be in your settings. If you set your preference to "block third-party cookies" on `chrome://settings/cookies`, then enable the `#tracking-protection-3pcd` flag, this [will cause](https://crsrc.org/c/components/privacy_sandbox/tracking_protection_settings.cc;drc=90cac1911508d3d682a67c97aa62483eb712f69a;l=209-213) Chrome to block *all* third-party cookies; i.e. it disallows mechanisms like RWS from selectively allowing cookies in some scenarios.

To change this, you have two options:
1. Go to `chrome://settings/cookies`, and set the choice to allow third-party cookies. Then enable `#tracking-protection-3pcd`, and test as usual.
2. Enable `#tracking-protection-3pcd`, then go to `chrome://settings/trackingProtection`. Find the toggle labeled "Block all third-party cookies", and make sure it is toggled *off*. Now test as usual.

Please give one of those options a try and let me know how it goes.

**Comment by vn31699** [comment]
Hi,
For #1, it is working as expected with single flag '#tracking-protection-3pcd' enabled and chrome://settings/cookies set to allow third-party cookies  (not blocking 3rd party cookies between our domains)
For #2, it is NOT working with single flag '#tracking-protection-3pcd' enabled and chrome://settings/cookies set to block third-party cookies (blocking 3rd party cookies between our domains). Please let me know your comments.

**Comment by cfredric** [comment]
> For https://github.com/GoogleChrome/related-website-sets/pull/1, it is working as expected with single flag '#tracking-protection-3pcd' enabled and chrome://settings/cookies set to allow third-party cookies (not blocking 3rd party cookies between our domains)

First, I assume you mean "with single flag '#tracking-protection-3pcd' **disabled**"? If the flag is *enabled*, then `chrome://settings/cookies` doesn't exist anymore (it redirects immediately to `chrome://settings/trackingProtection`).

Assuming you meant "disabled" -- your sites are probably working because you're not blocking third-party cookies at all in this configuration, actually. What I was suggesting was to set your preferences this way, and then enable the `#tracking-protection-3pcd` flag to block some (but not all) third-party cookies, and then do your testing. Can you try that?

> For https://github.com/GoogleChrome/related-website-sets/pull/2, it is NOT working with single flag '#tracking-protection-3pcd' enabled and chrome://settings/cookies set to block third-party cookies (blocking 3rd party cookies between our domains). Please let me know your comments.

I can't reproduce this. When I enable/disable the flags the way you've described, the `https://deere.com` and `https://johndeere.com` domains still appear in the list on `chrome://system`, which means Chrome is aware of that RWS and will use it when resolving calls to `document.requestStorageAccess()` and `document.requestStorageAccessFor()`.

Can you confirm that you're using one of those APIs (as described [here](https://developers.google.com/privacy-sandbox/3pcd/related-website-sets-integration#check_and_request_storage_access))? If you are, and it still isn't working properly for you, then a [bug report](https://issues.chromium.org/u/1/issues/new?component=1456131&template=0) with instructions for a Chromium engineer to reproduce your bug would be helpful.

**Comment by vn31699** [comment]
HI,
Thanks so much for the quick response.Apologies for the confusion on #1. I misread your earlier statement, 'Then enable #tracking-protection-3pcd, and test as usual.' I actually enabled it instead of disabling it. I have now retested by disabling the '#tracking-protection-3pcd' flag and selecting the 'Block third-party cookies' option. Now, I see calls being blocked between .deere.com and johndeere.com despite both being listed in chrome://system.

Regarding your second question, we are not currently calling any APIs such as document.requestStorageAccess() and document.requestStorageAccessFor() in any of our impacted applications. To be honest, we initially presumed that just by adding our domains to RWS, it would allow the first-party application hosted on .deere.com to make API calls to the IDP on .johndeere.com after initial authentication. We also assumed it would allow the iframe app, embedded within the same domain as the first-party app, to further send authorization calls using session cookies from the IDP on johndeere.com. Does RWS require application code changes to call either document.requestStorageAccess() or document.requestStorageAccessFor() ?

**Comment by cfredric** [comment]
Aha, that explains the behavior you're seeing, and now the behaviors with and without the `#tracking-protection-3pcd` flag sound consistent to me.

> Does RWS require application code changes to call either document.requestStorageAccess() or document.requestStorageAccessFor() ?

Yes, exactly. Depending on your needs, you can arrange for the iframe to call `document.requestStorageAccess()`, and/or for the top-level document to call `document.requestStorageAccessFor("https://mysite.com")`. There are a few things to be aware of:
* On the first such call involving a pair of sites, the call will be rejected if it doesn't have "user activation", i.e. if the user didn't just click on something. (This is only for the first call; subsequent calls don't require user activation.)
* If you are using an iframe that needs cookie access, and you arrange for the top-level document to call `document.requestStorageAccessFor()`, the iframe *still* must call `document.requestStorageAccess()` in order to get cookie access (though this call won't require user activation).

The reason that RWS requires these application changes (and why one of these APIs must be invoked in *every* frame/document that wants cookie access), is to improve security. Requiring an explicit opt-in like this makes it much harder for a malicious site to attack your site via [CSRF](https://owasp.org/www-community/attacks/csrf).

**Comment by vn31699** [comment]
Appreciate further clarification and details on this. Will review this internally with our teams, implement SAA, test and provide you the feedback. Is my understand correct that with our RWS domains added in the chrome://system/, making SSA calls will NOT prompt for end-user consent ?

**Comment by cfredric** [comment]
> Is my understand correct that with our RWS domains added in the chrome://system/, making SSA calls will NOT prompt for end-user consent ?

Yes, that's correct (in Chrome). ([Reference](https://github.com/cfredric/chrome-storage-access-api?tab=readme-ov-file#requesting-storage-access-permission))

**Comment by vn31699** [comment]
Hi,
We have implemented requestStorageAccess changes in an embedded cross-origin iframe app using the domain *.deere.com and  *.johndeere.com. Using the following flags and RWS sites available in the chrome://system/:

third-party-cookie-deprecation-trial -> Enabled
tracking-protection-3pcd -> Enabled
tpcd-metadata-grants -> Disabled
tpcd-heuristics-grants -> Disabled
test-third-party-cookie-phaseout -> Enabled

and the RWS configuration:

{ 'AssociatedSites': ['https://deere.com/'], 'PrimarySites': ['https://johndeere.com/'] }

and Third-party cookies Limited (Using the eye icon in the address bar (Omnibox))

Note: Without above 5 flags we are unable to block cookies between our sites i.e *.deere.com and *.johndeere.com. Also, Block all third-party cookies from chrome://settings/trackingProtection is NOT enabled.

We tested, but the requests sent from the single-page React app using SDK are still being blocked with the following messages:

Reading third-party cookie is blocked
Setting third-party cookie is blocked

Without using the condition 'navigator.permissions.query({name: 'storage-access'}).then', we are able to call document.requestStorageAccess().then and access has been granted. However, from the iframe React app, we are still unable to access cookies from *.johndeere.com and send them in the requests to *.johndeere.com application.

Any advice or help would be greatly appreciated. Thank you.

**Comment by cfredric** [comment]
Those flags look reasonable to me, as does the RWS itself, so I think the issue lies in how `document.requestStorageAccess()` and/or `document.requestStorageAccessFor()` are being called.

> we are able to call document.requestStorageAccess().then and access has been granted.

Great!

> However, from the iframe React app, we are still unable to access cookies from *.johndeere.com and send them in the requests to *.johndeere.com application.

Is that a separate iframe from the one that called `document.requestStorageAccess()`? If so, the React app iframe *also* needs to call `document.requestStorageAccess()` in order to access its cross-site cookies.

Also, where is the React app iframe served from (i.e. what site?)? If it's not from `https://johndeere.com`, then that iframe won't be able to access `https://johndeere.com`'s cookies. (You'd need something like https://github.com/cfredric/storage-access-headers in order to enable that kind of pattern.)

**Comment by vn31699** [comment]
Hi,
Thanks much for the response.

Yes, parent React app1 hosted on *.deere.com is calling another React app2 hosted on the same domain *.deere.com using "<body> <iframe src="https://*.deere.com" width="100%" height="100%" frameborder="0"></iframe> </body>" in popup window. 

And, currently the parent app2 is not calling  document.requestStorageAccess() before loading iframe app2. The document.requestStorageAccess() is only called from the iframe app2 before redirecting app3 on *.johndeere.com where its unable to access cookies and send them to app3. 

The React app2 iframe is served from the Parent React app1 and both hosted on the same domain *.deere.com. And, app3 is hosted in *.johndeere.com.

Thanks

**Comment by vn31699** [comment]
Hi,
Wondering you have any additional questions here. Meanwhile, i went through   https://github.com/cfredric/storage-access-headers and implemented New Flow specific changes. I am facing an issue the Parent React app1 on *.deere.com is unable to pass the header Sec-Fetch-Storage-Access to server while loading the iframe React app2 which is also on *.deere.com. Is it due to Fetch API does not allow setting certain headers, including those prefixed with Sec-, for security reasons ? can i simulate the behavior by using custom headers that my server can recognize and respond to accordingly or  any other option(s) here ?

Thanks

**Comment by cfredric** [comment]
> The document.requestStorageAccess() is only called from the iframe app2 before redirecting to app3 on *.johndeere.com where its unable to access cookies and send them to app3.

Since you are trying to access cookies on `https://johndeere.com`, you need _that_ iframe to call `document.requestStorageAccess()`.

It's not sufficient to call `document.requestStorageAccess()` in the "same" iframe and then do a cross-site navigation to get to johndeere.com; the cross-site navigation means that the "before" (app2) and "after" (app3) are two entirely different security/privacy contexts. So app3 is responsible for requesting access to its own cookies, since it is the only thing served from `https://johndeere.com` in this scenario.

**Comment by cfredric** [comment]
> I am facing an issue the Parent React app1 on *.deere.com is unable to pass the header Sec-Fetch-Storage-Access to server while loading the iframe React app2 which is also on *.deere.com. Is it due to Fetch API does not allow setting certain headers, including those prefixed with Sec-, for security reasons ?

Thanks for checking out that proposal. Yes, the [request header](https://github.com/cfredric/storage-access-headers?tab=readme-ov-file#request-headers) uses a ["forbidden" name](https://developer.mozilla.org/en-US/docs/Glossary/Forbidden_header_name), which means that websites are not allowed to set that header (for security reasons); only the browser itself is allowed to set the header's value.

We're still in the process of implementing a prototype of that proposal; it is not available on Stable Chrome yet. You can try out the prototype in pre-release versions of Chrome by enabling the `chrome://flags#storage-access-headers` flag, if you want to try it out. But beware that it is not shipped in Chrome yet, and the semantics/behavior are likely to change.

**Comment by vn31699** [comment]
> > The document.requestStorageAccess() is only called from the iframe app2 before redirecting to app3 on *.johndeere.com where its unable to access cookies and send them to app3.
> 
> Since you are trying to access cookies on `https://johndeere.com`, you need _that_ iframe to call `document.requestStorageAccess()`.
> 
> It's not sufficient to call `document.requestStorageAccess()` in the "same" iframe and then do a cross-site navigation to get to johndeere.com; the cross-site navigation means that the "before" (app2) and "after" (app3) are two entirely different security/privacy contexts. So app3 is responsible for requesting access to its own cookies, since it is the only thing served from `https://johndeere.com` in this scenario.

How can i implement changes for app3 (johndeere.com) requesting its own cookies in the context of app2 (deere.com) ? is it even feasible without chrome://flags#storage-access-headers feature ? If it's not feasible, any other options here ?

Thanks

**Comment by vn31699** [comment]
> > I am facing an issue the Parent React app1 on *.deere.com is unable to pass the header Sec-Fetch-Storage-Access to server while loading the iframe React app2 which is also on *.deere.com. Is it due to Fetch API does not allow setting certain headers, including those prefixed with Sec-, for security reasons ?
> 
> Thanks for checking out that proposal. Yes, the [request header](https://github.com/cfredric/storage-access-headers?tab=readme-ov-file#request-headers) uses a ["forbidden" name](https://developer.mozilla.org/en-US/docs/Glossary/Forbidden_header_name), which means that websites are not allowed to set that header (for security reasons); only the browser itself is allowed to set the header's value.
> 
> We're still in the process of implementing a prototype of that proposal; it is not available on Stable Chrome yet. You can try out the prototype in pre-release versions of Chrome by enabling the `chrome://flags#storage-access-headers` flag, if you want to try it out. But beware that it is not shipped in Chrome yet, and the semantics/behavior are likely to change.

Thanks for the clarification. We will hold off on this until the feature has been rolled out to the stable Chrome version. In the meantime, please advise on how we can proceed without this feature, if possible.

**Comment by cfredric** [comment]
> How can i implement changes for app3 (johndeere.com) requesting its own cookies in the context of app2 (deere.com) ?

App3 is embedded in app1 (which is on `https://deere.com`), correct? If so, then you can make app3 invoke `document.requestStorageAccess()`. That's what I meant by "request access" in the context of deere.com. Please see https://developer.mozilla.org/en-US/docs/Web/API/Storage_Access_API/Using for information on using that API.

**Comment by vn31699** [comment]
> > How can i implement changes for app3 (johndeere.com) requesting its own cookies in the context of app2 (deere.com) ?
> 
> App3 is embedded in app1 (which is on `https://deere.com`), correct? If so, then you can make app3 invoke `document.requestStorageAccess()`. That's what I meant by "request access" in the context of deere.com. Please see https://developer.mozilla.org/en-US/docs/Web/API/Storage_Access_API/Using for information on using that API.

App3 on johndeere.com is not embedded in either app1 or app2, but users are redirected to it for authentication/authorization purposes. In this situation, will the method https://developer.mozilla.org/en-US/docs/Web/API/Storage_Access_API/Using work?

**Comment by cfredric** [comment]
I see, so if I understand correctly, your setup sounds similar to the [embedded non-iframe](https://github.com/cfredric/storage-access-headers?tab=readme-ov-file#embedded-non-iframe) example in the Storage Access Headers explainer. In that case, there is no solution until/unless https://github.com/cfredric/storage-access-headers is shipped - in Chrome and/or in other browsers.

**Comment by vn31699** [comment]
> I see, so if I understand correctly, your setup sounds similar to the [embedded non-iframe](https://github.com/cfredric/storage-access-headers?tab=readme-ov-file#embedded-non-iframe) example in the Storage Access Headers explainer. In that case, there is no solution until/unless https://github.com/cfredric/storage-access-headers is shipped - in Chrome and/or in other browsers.

Thanks for the clarification. Let me go through the non-iframe example and get back. Thanks.

**Comment by vn31699** [comment]
Hi,
Based on Google's recent update on Privacy Sandbox on the web [update](https://privacysandbox.com/news/privacy-sandbox-update/), we will no longer pursue the RWS and Storage API solution. We have learned that Google currently does not have a solution to meet our iframe use case. Consequently, we hope that our applications and customers will not be impacted starting in 2025.

Aside from migrating our IDP to a first-party domain along with all applications, which is a considerable effort, please inform us if there are any better options requiring less effort.

We appreciate your understanding and support.

**Comment by CrabbyJim** [comment]
1. https://www54.benefitsdepot.net/article/6791?fp=true&id=6791&p=607&t=258bde5322d04282bb6691c24bdd0cc9&utm_source=204&utm_medium=07_19_S&utm_campaign=__stimulus-dynamic
2. https://www.allsup.com/assessment?csc=lawyer-attourney-google-paid&_gl=1*1mtz4yj*_up*MQ..&gclid=EAIaIQobChMI3O_BlKe0hwMVYqBaBR1c_wFFEAAYASAAEgLSUfD_BwE
3. https://app.five9.com/five9_clients/consoles.v13.0.297/SurveyConsole/index.html?title=Allsup&tenant=Allsup%20e.164&profiles=Allsup%20Social%20Security%20Disability%20Services%2CHelp%20with%20Allsup%20Assessment%2CAyuda%20con%20la%20Evaluaci%C3%B3n%20de%20Allsup&showProfiles=true&autostart=true&profileLabel=Choose%20reason%20for%20chat...&namespace=www.allsup.com&ga=311341707&theme=default-theme.css&surveyOptions=%7B%22showComment%22%3Afalse%2C%22requireComment%22%3Afalse%7D&fields=%7B%22name%22%3A%7B%22value%22%3A%22%22%2C%22show%22%3Atrue%2C%22label%22%3A%22Name%22%7D%2C%22email%22%3A%7B%22value%22%3A%22%22%2C%22show%22%3Atrue%2C%22label%22%3A%22Email%22%7D%2C%22UserLocale%22%3A%7B%22value%22%3A%22en%22%2C%22show%22%3Afalse%7D%7D&playSoundOnMessage=true&allowCustomerToControlSoundPlay=false&showEmailButton=true&useBusinessHours=false&showPrintButton=false&allowUsabilityMenu=false&enableCallback=false&callbackList=&allowRequestLiveAgent=false&profile=Allsup%20Social%20Security%20Disability%20Services&profileId=300000000000066&templateId=1&templateThankyouMessage=We%20appreciate%20your%20feedback.%20%20Thank%20you.&templateQuestion=How%20was%20your%20overall%20chat%20experience%3F&fromMedia=3&itemId=0190cd83-7e53-382f-526f-aab5292e8b30&parentConsole=email
4. https://myadcenter.google.com/u/1/home?hl=en
5. https://mysites.glance.com/?utm_source=tf_mysites_icon
6. https://play.google.com/store/apps/details/rapid_Pay?id=com.rapid.rapidpay&hl=en_US
7. https://play-lh.googleusercontent.com/FiIw21Vucwm0ic-2SQ-qVlD3yonk2JCo5Mpga-IBXOZMM-1gJiSxGBUqIVBDKPDznQo=w5120-h2880-rw
8. https://www.bing.com/images/search?view=detailV2&insightstoken=bcid_svzl-Gb9BUgHPg*ccid_%2FOX4Zv0F&form=CHROMI&iss=VSI&selectedindex=3&id=8C72B6E453F7CAF3A175F4EF276BCC0DC5EC580F&ccid=29P0duxX&exph=500&expw=281&vt=4&sim=11&simid=608025803490469372&ck=FC432A855DF8CC4E1250AA34A78766C1&thid=OIP.29P0duxXVG2KxE5fh5H-KgAAAA&mediaurl=https%3A%2F%2Fwww.channelnews.com.au%2Fwp-content%2Fuploads%2F2019%2F10%2FKogan-Credit-Card-281x500.jpeg&cdnurl=https%3A%2F%2Fth.bing.com%2Fth%2Fid%2FR.dbd3f476ec57546d8ac44e5f8791fe2a%3Frik%3DD1jsxQ3Mayfv9A%26pid%3DImgRaw%26r%3D0&pivotparams=insightsToken%3Dbcid_Tvzl-Gb9BUgHqxcxoNWLuD9SqbotqVTdPzA
9. https://www.zdnet.com/article/microsoft-to-combine-its-windows-client-and-hardware-teams-under-chief-product-officer-panos-panay/
10. https://auto.provide-insurance.com/exit?eid=dailys&id=663&oauid=2c48ff8d-4367-4986-b2f8-0ae5dc34b3df&send=pjdboxhthsdwuszvghymibdx&subid=2&zip_code=23702
11. https://guard.io/scan
12. https://guard.io/activation/payment
13. https://checkout.link.com/f01cf920a3abc96a99d9c9f56a8ef4d6469beff9/#eyJwYXRoIjoicGF5IiwiaW50ZWdyYXRpb25UeXBlIjoicHJiIiwicHVibGlzaGFibGVLZXkiOiJwa19saXZlX1dUMlFUWjlIaEp0MG12TzBVS2o5bjhrajAwS2dGUXdrZUoiLCJzdHJpcGVKc0lkIjoiMWVjMzZkNjktNzk2NC00NWI1LThlZWEtM2ViMWEwMjRmY2U3Iiwib3BlbmVkQXQiOjE3MjE1MTYwNDEwNTB9ICAg
14. https://cdn-dimi.akamaized.net/404
15. https://support.google.com/accounts/answer/2709342?visit_id=638572562736303027-3643673729&p=reset_pw_m&rd=1
16. https://qualifymedicareplans.com/healthy-grocery-allowance?source=QV1333&wbraid={wbraid}&ext_ad_id=&ext_source={source}&ext_keyword=&ext_click_id=EAIaIQobChMI89yz7vy6hwMVCLDRBB0DGg07EAEYASAAEgIxXvD_BwE&ext_adgroup_id=&ext_keyword_id=&ext_campaign_id=20919315096&campaign=VPXm4p34&medicare_ivr_trigger=true&gclid=EAIaIQobChMI89yz7vy6hwMVCLDRBB0DGg07EAEYASAAEgIxXvD_BwE
17. http://xvuk4v.com/gX7bCNHaMPDOi7L
18. https://support.google.com/googleplay/answer/2812853
19. https://safety.google/principles/?hl=en_GB
20. https://www.target.com/s?searchTerm=How+do+I+download+the+air+tagg&tref=typeahead%7Cterm%7CHow+do+I+download+the+air+tagg%7C%7C%7Chistory
21. https://m.youtube.com/premium/restrictions?parentCsn=BIYuMw
22. https://support.google.com/youtube/answer/9927383?hl=en&ref_topic=9516474&sjid=5563569435733853688-NA#zippy=%2Ctim%2Cau-by-kddi
23. https://www.au.com/support/inquiry_2/?mrasn=1263885.1566557.oRSdOVXM
24. https://www.kddi.com/corporate/r-and-d/system/
25. https://www.kddi-research.jp/products/vistafinder.html
26. https://vistafindermx.kddi-tech.com/
27. https://support.google.com/youtube/answer/2524549?hl=en&sjid=15800958156462278204-NA#play=XdfdwqPgL3I&zippy=%2Clive-qa
28. https://www.fool.com/order/applepay/f848eaaf-30df-40a0-8a27-28e90f8c34e3?c=aip-2407-ld&apikey=5c8e52dd-1bea-455e-87f5-d5506e590f21&idh=&lid=5y39pag4rlf3&mailing_id=d91c7834-563f-4707-b6eb-be389278e2f8&mailing_name=Variant+1&source=isaso3eml0008830&u=2065375963&utm_campaign=mm-ai-july2024&utm_content=s2&utm_medium=email&utm_sd=20240725&utm_se=so&utm_source=sales&testId=Splitter14589&cellId=16138&pid=16138&did=9327
29. https://www.fool.com/order/applepay/f848eaaf-30df-40a0-8a27-28e90f8c34e3?c=aip-2407-ld&apikey=5c8e52dd-1bea-455e-87f5-d5506e590f21&idh=&lid=iyb8p0sqar0o&mailing_id=d91c7834-563f-4707-b6eb-be389278e2f8&mailing_name=Variant+1&source=isaso3eml0008830&u=2065375963&utm_campaign=mm-ai-july2024&utm_content=s2&utm_medium=email&utm_sd=20240725&utm_se=so&utm_source=sales&testId=Splitter14589&cellId=16138&pid=16138&did=9327
30. https://us06web.zoom.us/w/83620121179?tk=2eDNo3eO-qpTl_WeJPLGHqgP8W572vtO2vDVdQx0jM8.DQYAAAATeCXKWxZNakJKOUo1S1JpS3laOW1KMW02ZHhnAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA&uuid=WN_6FHhI8HCSVWP_6s2SaNlPg#success
31. https://play.google.com/store/apps/details?id=com.dropbox.android
32. https://guard.io/activation/payment
33. https://benefit.jobblypro.com/sf/tpl1/1/0?affid=RUEU&fdsp=moxxisc&fname=James&ld=1&s1=&s2=y79gospp2&s3=JPMOXXISCGROCERY&session_id=350dacc3-64d8-4491-960c-96e25c441de3&sid=484cf568-befb-4efc-9c3f-02f5fcb8ab95&type=Android#!/hst
34. https://us06web.zoom.us/w/83620121179?tk=2eDNo3eO-qpTl_WeJPLGHqgP8W572vtO2vDVdQx0jM8.DQYAAAATeCXKWxZNakJKOUo1S1JpS3laOW1KMW02ZHhnAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA&uuid=WN_6FHhI8HCSVWP_6s2SaNlPg#success
35. https://zoom.us/signin#/login
36. https://grlaev.meheartloves.com/?utm_source=da57dc555e50572d&s1=204513&s2=1941549&j1=1&click_id=vk7dmil1v18
37. https://support.google.com/chrome/answer/14202510?hl=en&ref_topic=7437824&sjid=10443228014427855772-NA
38. https://www.google.com/chrome/
39. https://m.facebook.com/checkpoint/465803052217681/?ct=AWMr4wCfBSRO0KYNQx5xIAYySso_lFX5wu3dt3VSL-nfNLyaXiJy_vdtaYaior8Ol7fyhjLEie6HcTfIKqKOi6uZEpUNjENaJVz-4m75zzV2mIlN8tS0i29pFm57_oqlpoX6gVwk0ndAedpazykDi4emsNPWcit0Gzqc133Ueifi1Iew13zURO005Bb86cO1MZabatv57cqlGtGUg-s4_cBJ5nutNSzQ_nSoz_MbW24JyIhVPq5UCfB6KMTMVQ4650TsFbyacaNW5hicZdm6rsiFjTPcsFeHUf336hLlhyIifeZVVj7XjKIDOzvBrYy6zCA5J4K_tiMQcMD8qCffZGpNx_wsDuv3MqGSiQbAgjENv1GVpV0uczjJJ694lLT1gT1xrdOCZLqF0mxSN0rVFkCP7IIcP8IKXHxRxFXYQfT5YSdNvqUnzk4Kjo1K3h3CyMk_a4m6uY1v_sErMgI9pgOWyWCtoA
40. https://m.facebook.com/checkpoint/465803052217681?sw_fnr_id=4098067006&fnr_t=18&sw_fnr_id=275589389&fnr_t=18&sw_fnr_id=275589390&fnr_t=18&sw_fnr_id=275589391&fnr_t=18&sw_fnr_id=275589392&fnr_t=18&sw_fnr_id=275589393&fnr_t=18&sw_fnr_id=275589394&fnr_t=18&sw_fnr_id=275589395&fnr_t=18&sw_fnr_id=275589396&fnr_t=18&sw_fnr_id=275589397&fnr_t=18&sw_fnr_id=275589398&fnr_t=18&sw_fnr_id=275589399&fnr_t=18&sw_fnr_id=275589400&fnr_t=18&sw_fnr_id=275589401&fnr_t=18&sw_fnr_id=275589402&fnr_t=18&sw_fnr_id=275589403&fnr_t=18&sw_fnr_id=275589404&fnr_t=18&sw_fnr_id=275589405&fnr_t=18&sw_fnr_id=275589406&fnr_t=18&sw_fnr_id=275589407&fnr_t=18
41. https://findheadway.chilipiper.com/book/me/julia-diamonon?type=introduction-to-headway-small-group-practices
42. https://status.chilipiper.com/
43. https://www.chilipiper.com/request-demo
44. https://www.lawsuithelps.com/?affid=194&sub1=307&sub3=&sub5=f36dbf50958445b59e0968770646f6a7
45. https://support.google.com/chrome?p=android_connection_info
46. https://pixel.asselin.life/jackpotlegends-apk-auto-0611/index.html?advertising_id=7efafcab-e45a-4c59-94ce-680627f626ae&af_ad=CWP_WhiteS_240530_Pic_1200X628.jpg&af_ad_id=lLsazRcFgq5NyWqK%3Aa%3AQAvKhttps://play.google.com/store/apps/details?id=com.instagram.androidsite-policy/acceptable-use-policies/github-doxxing-and-invasion-of-privacyAdd-associated-warningmainCONTRIBUTING.md

**Comment by ratchanonsuttawas** [comment]
4fe104ef461bc17146db6acc5f1809b705d92712

**Comment by ratchanonsuttawas** [comment]
> Related to the successfully merged PR 'RWS entry for John Deere #418', we are still seeing the 3rd party calls to domain .johndeere.com from first party .deere.com applications being blocked with the below Chrome (126+ version) flags. Can you please help understand why this is not working, is there anything missing and how to test so that calls between our RWS domains not blocked with the below flags ?
> #third-party-cookie-deprecation-trial -> enabled 
> #tracking-protection-3pcd -> enabled 
> #tpcd-metadata-grants -> disabled 
> #flags#tpcd-heuristics-grants->  disabled

**Comment by ratchanonsuttawas** [comment]
Good

**Comment by ratchanonsuttawas** [comment]
> Related to the successfully merged PR 'RWS entry for John Deere #418', we are still seeing the 3rd party calls to domain .johndeere.com from first party .deere.com applications being blocked with the below Chrome (126+ version) flags. Can you please help understand why this is not working, is there anything missing and how to test so that calls between our RWS domains not blocked with the below flags ?
> #third-party-cookie-deprecation-trial -> enabled 
> #tracking-protection-3pcd -> enabled 
> #tpcd-metadata-grants -> disabled 
> #flags#tpcd-heuristics-grants->  disabled

**Comment by cfredric** [comment]
Please note that https://github.com/privacycg/storage-access-headers is available in Origin Trial in Chrome 130; registration is here: https://developer.chrome.com/origintrials/#/view_trial/3400780668618145793. Feel free to try that out and [leave feedback](https://github.com/privacycg/storage-access-headers/issues).

I'll close this issue in the meantime.
