### ISSUE TITLE
Broken link in getting-started.md

### ISSUE THREAD

**Issue by jgarite** [GoogleChrome/related-website-sets#432]
In step 2 on the Getting Started file: 
https://github.com/GoogleChrome/related-website-sets/blob/main/Getting-Started.md#step-2-creating-or-updating-your-rws-submission
in point # 3, the link for "format" is leading to a 404 page (https://github.com/GoogleChrome/first-party-sets/blob/main/FPS-Submission_Guidelines.md#set-submissions).

**Comment by sjledoux** [comment]
Thank you for pointing this out. The link should go to [the Set Submission section of the submisison guidelines](https://github.com/GoogleChrome/first-party-sets/blob/main/RWS-Submission_Guidelines.md#set-submissions), which contains the schema that is used for submission validation. We'll fix this shortly.

**Comment by sjledoux** [comment]
Fixed in #451
