### ISSUE TITLE
Some discrepancies and suggestions on the different JSON schemas specified in this repo

### ISSUE THREAD

**Issue by yohhaan** [GoogleChrome/related-website-sets#506]
Hello,

I have noticed a few discrepancies in the JSON schemas that are specified in this repository, you will find next a list of comments with some suggestions. I am submitting this as an issue rather than a pull request as per the [FAQs](https://github.com/GoogleChrome/related-website-sets/blob/main/Getting-Started.md#faqs). Also, a note: I have not checked if the automated tests need to be updated in some way accordingly to these suggested changes.

## In [`SCHEMA.json`](https://github.com/GoogleChrome/related-website-sets/blob/main/SCHEMA.json):

- `"contact" : {"type": "string"},` should be listed under the properties for  the nested list of objects under `"sets"` and not for the global object as it currently is.
- additionally, the `"oneOf"` keyword could also be used the following way to  make sure that at least one of these 3 entries is present:
    ```json
    "oneOf": [
            {
                "required": [
                    "associatedSites"
                ]
            },
            {
                "required": [
                    "serviceSites"
                ]
            },
            {
                "required": [
                    "ccTLDs"
                ]
            }
        ],
    ```
- This would give the following updated schema:

```json
{
    "type": "object",
    "properties": {
        "sets": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "contact": {
                        "type": "string"
                    },
                    "ccTLDs": {
                        "type": "object",
                        "additionalProperties": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    },
                    "primary": {
                        "type": "string"
                    },
                    "associatedSites": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    },
                    "serviceSites": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    },
                    "rationaleBySite": {
                        "type": "object",
                        "additionalProperties": {
                            "type": "string"
                        }
                    }
                },
                "required": [
                    "primary",
                    "contact"
                ],
                "oneOf": [
                    {
                        "required": [
                            "associatedSites"
                        ]
                    },
                    {
                        "required": [
                            "serviceSites"
                        ]
                    },
                    {
                        "required": [
                            "ccTLDs"
                        ]
                    }
                ],
                "dependentRequired": {
                    "associatedSites": [
                        "rationaleBySite"
                    ],
                    "serviceSites": [
                        "rationaleBySite"
                    ]
                }
            }
        }
    }
}
```

## In [RWS-Submission_Guidelines.md](https://github.com/GoogleChrome/related-website-sets/blob/main/RWS-Submission_Guidelines.md)

- First schema under [#set-submissions](https://github.com/GoogleChrome/related-website-sets/blob/main/RWS-Submission_Guidelines.md#set-submissions):
  - It does not have `"contact"` as  `"required"`.
  - For consistency, if you add the `"oneOf"` keyword to [`SCHEMA.json`](https://github.com/GoogleChrome/related-website-sets/blob/main/SCHEMA.json), it should also be added here.

- The example and the schema for the primary set does not contain `"contact" :
  {"type": "string"},` anymore.
  - Is there a reason why contact is not required in the well-known file hosted at the primary domain?
  - It would likely make things easier if it were required in both places: canonical sets file on GitHub and hosted well-known primary files. If so, schemas and examples need to be updated to reflect this.

## Other Misc

Under [#set-level-technical-validation](https://github.com/GoogleChrome/related-website-sets/blob/main/RWS-Submission_Guidelines.md#set-level-technical-validation):

- The formatting of the example URLs/filenames with the back quotes is incorrect  as well as some Markdown links.

- It does not seem that the 2 paths in bold in the following quote are supposed  to be the same, right?

    > The primary domain must serve a JSON file at **/.well-known/related-website-set.json** (Note: list entries merged before September 15th 2023 may serve their well-known file at **/.well-known/related-website-set.json** instead; however, any changes to those entries will require that the primary and all members of the set must be served at /.well-known/related-website-set.json like any other entry). The contents of the file must be identical to the submission. Each member domain must serve a JSON file at /.well-known/related-website-set.json. The contents of the file must name the primary domain. These files must be maintained for the duration of the domain’s inclusion in the set.

Best regards,

Yohan

**Comment by Dani-ops923** [comment]
Esse esquema Jason está usando e criando coisas ruins, que, inclusive usa o site de vcs pra se beneficiar e causa danos aos usuários, incluindo eu! Só quer ganhar dinheiro e está difamando o site de vcs, agindo de má fé.

**Comment by Dani-ops923** [comment]
Inclusive ele estava me pedindo de fazer o meu login no site de vocês

**Comment by shuranhuang** [comment]
Hi Yohan, thank you for the feedback. We'll take a closer look and get back.

**Comment by cfredric** [comment]
Hi Yohan,

I've updated the schema (#705) and the file path (#706), thanks for pointing out those issues.

Re: requiring the `contact` field in the JSON that's served by each of the sites (including the primary site), can you explain why you think that ought to be required?

Our reasoning for requiring a `contact` field in the list entries themselves is to give the repository maintainers a way to contact the entry authors via their preferred channel (e.g. a list alias, rather than a GitHub account). I'm not sure what purpose the `contact` field would serve in the JSON responses themselves, or what the consequence of a "mismatch" should be?

(For what it's worth, our automation doesn't care about unexpected fields in those JSON responses; so it's totally fine, from our perspective, to include the `contact` field if you want to.)

**Comment by yohhaan** [comment]
Hello Chris, 

Nice, good to see that the suggestions were helpful. 

And for the `contact` field, sounds good. I did not have a specific reason in mind other than just keep it consistent between submitted and hosted sets. Closing the issue. 

Best,
