### ISSUE TITLE
Setup Dependabot

### ISSUE THREAD

**Issue by arichiv** [GoogleChrome/related-website-sets#689]
https://github.com/dependabot

**Comment by arichiv** [comment]
@cfredric can I have admin rights to do this? Otherwise, could you do so?

**Comment by cfredric** [comment]
Dependabot alerts and dependabot security alerts were already enabled; I just enabled dependabot version updates (LMK if I did the yml file correctly, I haven't done that before).

**Comment by arichiv** [comment]
I cannot tell as I am not an admin, but it looks fine to me.
